<?php

namespace App;

class Country
{
    /**
     * Get all country
     * @return array
     */
    
    public static function all()
    {
        return [
            ['4', 'AFG', 'AF', 'Afghanistan'],
            ['710', 'ZAF', 'ZA', 'Afrique du Sud'],
            ['248', 'ALA', 'AX', 'Aland'],
            ['8', 'ALB', 'AL', 'Albanie'],
            ['12', 'DZA', 'DZ', 'Algérie'],
            ['276', 'DEU', 'DE', 'Allemagne'],
            ['20', 'AND', 'AD', 'Andorre'],
            ['24', 'AGO', 'AO', 'Angola'],
            ['660', 'AIA', 'AI', 'Anguilla'],
            ['10', 'ATA', 'AQ', 'Antarctique'],
            ['28', 'ATG', 'AG', 'Antigua-et-Barbuda'],
            ['682', 'SAU', 'SA', 'Arabie saoudite'],
            ['32', 'ARG', 'AR', 'Argentine'],
            ['51', 'ARM', 'AM', 'Arménie'],
            ['533', 'ABW', 'AW', 'Aruba'],
            ['36', 'AUS', 'AU', 'Australie'],
            ['40', 'AUT', 'AT', 'Autriche'],
            ['31', 'AZE', 'AZ', 'Azerbaïdjan'],
            ['44', 'BHS', 'BS', 'Bahamas'],
            ['48', 'BHR', 'BH', 'Bahreïn'],
            ['50', 'BGD', 'BD', 'Bangladesh'],
            ['52', 'BRB', 'BB', 'Barbade'],
            ['112', 'BLR', 'BY', 'Biélorussie'],
            ['56', 'BEL', 'BE', 'Belgique'],
            ['84', 'BLZ', 'BZ', 'Belize'],
            ['204', 'BEN', 'BJ', 'Bénin'],
            ['60', 'BMU', 'BM', 'Bermudes'],
            ['64', 'BTN', 'BT', 'Bhoutan'],
            ['68', 'BOL', 'BO', 'Bolivie'],
            ['535', 'BES', 'BQ', 'Bonaire', ' Saint-Eustache et Saba'],
            ['70', 'BIH', 'BA', 'Bosnie-Herzégovine'],
            ['72', 'BWA', 'BW', 'Botswana'],
            ['74', 'BVT', 'BV', 'Île Bouvet'],
            ['76', 'BRA', 'BR', 'Brésil'],
            ['96', 'BRN', 'BN', 'Brunei'],
            ['100', 'BGR', 'BG', 'Bulgarie'],
            ['854', 'BFA', 'BF', 'Burkina Faso'],
            ['108', 'BDI', 'BI', 'Burundi'],
            ['136', 'CYM', 'KY', 'Îles Caïmans'],
            ['116', 'KHM', 'KH', 'Cambodge'],
            ['120', 'CMR', 'CM', 'Cameroun'],
            ['124', 'CAN', 'CA', 'Canada'],
            ['132', 'CPV', 'CV', 'Cap-Vert'],
            ['140', 'CAF', 'CF', 'République centrafricaine'],
            ['152', 'CHL', 'CL', 'Chili'],
            ['156', 'CHN', 'CN', 'Chine'],
            ['162', 'CXR', 'CX', 'Île Christmas'],
            ['196', 'CYP', 'CY', 'Chypre'],
            ['166', 'CCK', 'CC', 'Îles Cocos'],
            ['170', 'COL', 'CO', 'Colombie'],
            ['174', 'COM', 'KM', 'Comores'],
            ['178', 'COG', 'CG', 'République du Congo'],
            ['180', 'COD', 'CD', 'République démocratique du Congo'],
            ['184', 'COK', 'CK', 'Îles Cook'],
            ['410', 'KOR', 'KR', 'Corée du Sud'],
            ['408', 'PRK', 'KP', 'Corée du Nord'],
            ['188', 'CRI', 'CR', 'Costa Rica'],
            ['384', 'CIV', 'CI', 'Côte d\'Ivoire'],
            ['191', 'HRV', 'HR', 'Croatie'],
            ['192', 'CUB', 'CU', 'Cuba'],
            ['531', 'CUW', 'CW', 'Curaçao'],
            ['208', 'DNK', 'DK', 'Danemark'],
            ['262', 'DJI', 'DJ', 'Djibouti'],
            ['214', 'DOM', 'DO', 'République dominicaine'],
            ['212', 'DMA', 'DM', 'Dominique'],
            ['818', 'EGY', 'EG', 'Égypte'],
            ['222', 'SLV', 'SV', 'Salvador'],
            ['784', 'ARE', 'AE', 'Émirats arabes unis'],
            ['218', 'ECU', 'EC', 'Équateur'],
            ['232', 'ERI', 'ER', 'Érythrée'],
            ['724', 'ESP', 'ES', 'Espagne'],
            ['233', 'EST', 'EE', 'Estonie'],
            ['840', 'USA', 'US', 'États-Unis'],
            ['231', 'ETH', 'ET', 'Éthiopie'],
            ['238', 'FLK', 'FK', 'Îles Malouines'],
            ['234', 'FRO', 'FO', 'Îles Féroé'],
            ['242', 'FJI', 'FJ', 'Fidji'],
            ['246', 'FIN', 'FI', 'Finlande'],
            ['250', 'FRA', 'FR', 'France'],
            ['266', 'GAB', 'GA', 'Gabon'],
            ['270', 'GMB', 'GM', 'Gambie'],
            ['268', 'GEO', 'GE', 'Géorgie'],
            ['239', 'SGS', 'GS', 'Géorgie du Sud-et-les Îles Sandwich du Sud'],
            ['288', 'GHA', 'GH', 'Ghana'],
            ['292', 'GIB', 'GI', 'Gibraltar'],
            ['300', 'GRC', 'GR', 'Grèce'],
            ['308', 'GRD', 'GD', 'Grenade'],
            ['304', 'GRL', 'GL', 'Groenland'],
            ['312', 'GLP', 'GP', 'Guadeloupe'],
            ['316', 'GUM', 'GU', 'Guam'],
            ['320', 'GTM', 'GT', 'Guatemala'],
            ['831', 'GGY', 'GG', 'Guernesey'],
            ['324', 'GIN', 'GN', 'Guinée'],
            ['624', 'GNB', 'GW', 'Guinée-Bissau'],
            ['226', 'GNQ', 'GQ', 'Guinée équatoriale'],
            ['328', 'GUY', 'GY', 'Guyana'],
            ['254', 'GUF', 'GF', 'Guyane'],
            ['332', 'HTI', 'HT', 'Haïti'],
            ['334', 'HMD', 'HM', 'Îles Heard-et-MacDonald'],
            ['340', 'HND', 'HN', 'Honduras'],
            ['344', 'HKG', 'HK', 'Hong Kong'],
            ['348', 'HUN', 'HU', 'Hongrie'],
            ['833', 'IMN', 'IM', 'Île de Man'],
            ['581', 'UMI', 'UM', 'Îles mineures éloignées des États-Unis'],
            ['92', 'VGB', 'VG', 'Îles Vierges britanniques'],
            ['850', 'VIR', 'VI', 'Îles Vierges des États-Unis'],
            ['356', 'IND', 'IN', 'Inde'],
            ['360', 'IDN', 'ID', 'Indonésie'],
            ['364', 'IRN', 'IR', 'Iran'],
            ['368', 'IRQ', 'IQ', 'Irak'],
            ['372', 'IRL', 'IE', 'Irlande'],
            ['352', 'ISL', 'IS', 'Islande'],
            ['376', 'ISR', 'IL', 'Israël'],
            ['380', 'ITA', 'IT', 'Italie'],
            ['388', 'JAM', 'JM', 'Jamaïque'],
            ['392', 'JPN', 'JP', 'Japon'],
            ['832', 'JEY', 'JE', 'Jersey'],
            ['400', 'JOR', 'JO', 'Jordanie'],
            ['398', 'KAZ', 'KZ', 'Kazakhstan'],
            ['404', 'KEN', 'KE', 'Kenya'],
            ['417', 'KGZ', 'KG', 'Kirghizistan'],
            ['296', 'KIR', 'KI', 'Kiribati'],
            ['414', 'KWT', 'KW', 'Koweït'],
            ['418', 'LAO', 'LA', 'Laos'],
            ['426', 'LSO', 'LS', 'Lesotho'],
            ['428', 'LVA', 'LV', 'Lettonie'],
            ['422', 'LBN', 'LB', 'Liban'],
            ['430', 'LBR', 'LR', 'Liberia'],
            ['434', 'LBY', 'LY', 'Libye'],
            ['438', 'LIE', 'LI', 'Liechtenstein'],
            ['440', 'LTU', 'LT', 'Lituanie'],
            ['442', 'LUX', 'LU', 'Luxembourg'],
            ['446', 'MAC', 'MO', 'Macao'],
            ['807', 'MKD', 'MK', 'Macédoine'],
            ['450', 'MDG', 'MG', 'Madagascar'],
            ['458', 'MYS', 'MY', 'Malaisie'],
            ['454', 'MWI', 'MW', 'Malawi'],
            ['462', 'MDV', 'MV', 'Maldives'],
            ['466', 'MLI', 'ML', 'Mali'],
            ['470', 'MLT', 'MT', 'Malte'],
            ['580', 'MNP', 'MP', 'Îles Mariannes du Nord'],
            ['504', 'MAR', 'MA', 'Maroc'],
            ['584', 'MHL', 'MH', 'Marshall'],
            ['474', 'MTQ', 'MQ', 'Martinique'],
            ['480', 'MUS', 'MU', 'Maurice'],
            ['478', 'MRT', 'MR', 'Mauritanie'],
            ['175', 'MYT', 'YT', 'Mayotte'],
            ['484', 'MEX', 'MX', 'Mexique'],
            ['583', 'FSM', 'FM', 'Micronésie'],
            ['498', 'MDA', 'MD', 'Moldavie'],
            ['492', 'MCO', 'MC', 'Monaco'],
            ['496', 'MNG', 'MN', 'Mongolie'],
            ['499', 'MNE', 'ME', 'Monténégro'],
            ['500', 'MSR', 'MS', 'Montserrat'],
            ['508', 'MOZ', 'MZ', 'Mozambique'],
            ['104', 'MMR', 'MM', 'Birmanie'],
            ['516', 'NAM', 'NA', 'Namibie'],
            ['520', 'NRU', 'NR', 'Nauru'],
            ['524', 'NPL', 'NP', 'Népal'],
            ['558', 'NIC', 'NI', 'Nicaragua'],
            ['562', 'NER', 'NE', 'Niger'],
            ['566', 'NGA', 'NG', 'Nigeria'],
            ['570', 'NIU', 'NU', 'Niue'],
            ['574', 'NFK', 'NF', 'Île Norfolk'],
            ['578', 'NOR', 'NO', 'Norvège'],
            ['540', 'NCL', 'NC', 'Nouvelle-Calédonie'],
            ['554', 'NZL', 'NZ', 'Nouvelle-Zélande'],
            ['86', 'IOT', 'IO', 'Territoire britannique de l\'océan Indien'],
            ['512', 'OMN', 'OM', 'Oman'],
            ['800', 'UGA', 'UG', 'Ouganda'],
            ['860', 'UZB', 'UZ', 'Ouzbékistan'],
            ['586', 'PAK', 'PK', 'Pakistan'],
            ['585', 'PLW', 'PW', 'Palaos'],
            ['275', 'PSE', 'PS', 'Autorité Palestinienne'],
            ['591', 'PAN', 'PA', 'Panama'],
            ['598', 'PNG', 'PG', 'Papouasie-Nouvelle-Guinée'],
            ['600', 'PRY', 'PY', 'Paraguay'],
            ['528', 'NLD', 'NL', 'Pays-Bas'],
            ['604', 'PER', 'PE', 'Pérou'],
            ['608', 'PHL', 'PH', 'Philippines'],
            ['612', 'PCN', 'PN', 'Îles Pitcairn'],
            ['616', 'POL', 'PL', 'Pologne'],
            ['258', 'PYF', 'PF', 'Polynésie française'],
            ['630', 'PRI', 'PR', 'Porto Rico'],
            ['620', 'PRT', 'PT', 'Portugal'],
            ['634', 'QAT', 'QA', 'Qatar'],
            ['638', 'REU', 'RE', 'La Réunion'],
            ['642', 'ROU', 'RO', 'Roumanie'],
            ['826', 'GBR', 'GB', 'Royaume-Uni'],
            ['643', 'RUS', 'RU', 'Russie'],
            ['646', 'RWA', 'RW', 'Rwanda'],
            ['732', 'ESH', 'EH', 'Sahara occidental'],
            ['652', 'BLM', 'BL', 'Saint-Barthélemy'],
            ['659', 'KNA', 'KN', 'Saint-Christophe-et-Niévès'],
            ['674', 'SMR', 'SM', 'Saint-Marin'],
            ['663', 'MAF', 'MF', 'Saint-Martin (Antilles françaises)'],
            ['534', 'SXM', 'SX', 'Saint-Martin'],
            ['666', 'SPM', 'PM', 'Saint-Pierre-et-Miquelon'],
            ['336', 'VAT', 'VA', 'Saint-Siège (État de la Cité du Vatican)'],
            ['670', 'VCT', 'VC', 'Saint-Vincent-et-les-Grenadines'],
            ['654', 'SHN', 'SH', 'Sainte-Hélène', ' Ascension et Tristan da Cunha'],
            ['662', 'LCA', 'LC', 'Sainte-Lucie'],
            ['90', 'SLB', 'SB', 'Salomon'],
            ['882', 'WSM', 'WS', 'Samoa'],
            ['16', 'ASM', 'AS', 'Samoa américaines'],
            ['678', 'STP', 'ST', 'Sao Tomé-et-Principe'],
            ['686', 'SEN', 'SN', 'Sénégal'],
            ['688', 'SRB', 'RS', 'Serbie'],
            ['690', 'SYC', 'SC', 'Seychelles'],
            ['694', 'SLE', 'SL', 'Sierra Leone'],
            ['702', 'SGP', 'SG', 'Singapour'],
            ['703', 'SVK', 'SK', 'Slovaquie'],
            ['705', 'SVN', 'SI', 'Slovénie'],
            ['706', 'SOM', 'SO', 'Somalie'],
            ['729', 'SDN', 'SD', 'Soudan'],
            ['728', 'SSD', 'SS', 'Soudan du Sud'],
            ['144', 'LKA', 'LK', 'Sri Lanka'],
            ['752', 'SWE', 'SE', 'Suède'],
            ['756', 'CHE', 'CH', 'Suisse'],
            ['740', 'SUR', 'SR', 'Suriname'],
            ['744', 'SJM', 'SJ', 'Svalbard et Île Jan Mayen'],
            ['748', 'SWZ', 'SZ', 'Swaziland'],
            ['760', 'SYR', 'SY', 'Syrie'],
            ['762', 'TJK', 'TJ', 'Tadjikistan'],
            ['158', 'TWN', 'TW', 'Taïwan / (République de Chine (Taïwan))'],
            ['834', 'TZA', 'TZ', 'Tanzanie'],
            ['148', 'TCD', 'TD', 'Tchad'],
            ['203', 'CZE', 'CZ', 'République tchèque'],
            ['260', 'ATF', 'TF', 'Terres australes et antarctiques françaises'],
            ['764', 'THA', 'TH', 'Thaïlande'],
            ['626', 'TLS', 'TL', 'Timor oriental'],
            ['768', 'TGO', 'TG', 'Togo'],
            ['772', 'TKL', 'TK', 'Tokelau'],
            ['776', 'TON', 'TO', 'Tonga'],
            ['780', 'TTO', 'TT', 'Trinité-et-Tobago'],
            ['788', 'TUN', 'TN', 'Tunisie'],
            ['795', 'TKM', 'TM', 'Turkménistan'],
            ['796', 'TCA', 'TC', 'Îles Turques-et-Caïques'],
            ['792', 'TUR', 'TR', 'Turquie'],
            ['798', 'TUV', 'TV', 'Tuvalu'],
            ['804', 'UKR', 'UA', 'Ukraine'],
            ['858', 'URY', 'UY', 'Uruguay'],
            ['548', 'VUT', 'VU', 'Vanuatu'],
            ['862', 'VEN', 'VE', 'Venezuela'],
            ['704', 'VNM', 'VN', 'Viêt Nam'],
            ['876', 'WLF', 'WF', 'Wallis-et-Futuna'],
            ['887', 'YEM', 'YE', 'Yémen'],
            ['894', 'ZMB', 'ZM', 'Zambie'],
            ['716', 'ZWE', 'ZW', 'Zimbabwe'],
        ];
    }
}